//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.27 at 06:03:57 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.emc.it.eis.IDS")
package com.emc.it.aveska.sap.reco.domain;
